version: '2'
services:
  eureka:
    image: 'eureka'
    hostname: eureka
    ports:
      - '8761:8761'
  picture-repo:
    image: 'picture-repo'
    environment:
      - EUREKA_URI=http://eureka:8761
    depends_on:
      - eureka
  ascii-generator:
    image: 'ascii-generator'
    environment:
      - EUREKA_URI=http://eureka:8761
    depends_on:
      - eureka
      - picture-repo
  frontend:
    image: 'frontend'
    environment:
      - EUREKA_URI=http://eureka:8761
    depends_on:
      - eureka
      - picture-repo
      - ascii-generator
