version: '2'
services:
  eureka:
    image: 'eureka'
    ports:
      - '8761:8761'
  picture-repo:
    image: 'picture-repo'
    ports:
      - '7777:7777'
    environment:
      - EUREKA_URI=http://eureka:8761
    depends_on:
      - eureka
  ascii-generator:
    image: 'ascii-generator'
    ports:
      - '8080:8080'
    environment:
      - EUREKA_URI=http://eureka:8761
    depends_on:
      - eureka
      - picture-repo
